# Generated by Django 5.1.1 on 2024-10-01 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_per_kg',
            new_name='prix_par_kg',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantite',
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('agriculture', 'Produits agricoles'), ('outillages', 'Outils'), ('machines', 'Machines')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
