# Generated by Django 5.1.1 on 2024-10-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='published_date',
            new_name='date_de_publication',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='titre',
        ),
    ]
