# Generated by Django 5.1.1 on 2024-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_de_telephone',
            field=models.CharField(max_length=15, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
